export const EducationData = {
    nauchitsya_chitat: {
      title: 'Научиться читать',
      description: 'А..Б..В.. а что дальше?',
      effects: { fun: 10 },
      initialPrice: 15,
      price: 15,
      displayPrice: '15$',
      currency: 'usdt',
      requiredLevel: 0,
    },
    treh_klassa: {
        title: '3 класса',
        description: 'Занимательно...',
        effects: { fun: 10 },
        initialPrice: 500,
        price: 500,
        displayPrice: '500$',
        currency: 'usdt',
        requiredLevel: 0,
        requirements: { education: ['nauchitsya_chitat'] },
    },
    devyat_klassov: {
        title: '9 классов',
        description: 'Подготовлюсь к ОГЭ!',
        effects: { fun: 10 },
        initialPrice: 5000,
        price: 5000,
        displayPrice: '5 000$',
        currency: 'usdt',
        requiredLevel: 0,
        requirements: { education: ['treh_klassa', 'nauchitsya_chitat'] },
    },
    srednee_obrazovanie: {
        title: 'Среднее образование',
        description: '11 лет позади...',
        effects: { fun: 10 },
        initialPrice: 20000,
        price: 20000,
        displayPrice: '20 000$',
        currency: 'usdt',
        requiredLevel: 0,
        requirements: { education: ['devyat_klassov', 'treh_klassa', 'nauchitsya_chitat'] },
    },
    ptu: {
        title: 'ПТУ',
        description: 'Сварщик — звучит не плохо',
        effects: { fun: 10 },
        initialPrice: 60000,
        price: 60000,
        displayPrice: '60 000$',
        currency: 'usdt',
        requiredLevel: 11,
        requirements: { education: ['srednee_obrazovanie', 'devyat_klassov', 'treh_klassa', 'nauchitsya_chitat'] },
    },
    vysshee_obrazovanie: {
        title: 'Высшее образование',
        description: 'Первые шаги в IT',
        effects: { fun: 10 },
        initialPrice: 2000,
        price: 2000,
        displayPrice: '2 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 13,
        requirements: { education: ['srednee_obrazovanie', 'devyat_klassov', 'treh_klassa', 'nauchitsya_chitat'] },
    },
    nanjat_repetitora: {
        title: 'Нанять репетитора',
        description: 'Основы крипто-рынка',
        effects: {},
        initialPrice: 1000,
        price: 1000,
        displayPrice: '1 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 21,
    },
    obrazovanie_zagr: {
        title: 'Образование за границей',
        description: 'Студент — звучит не плохо',
        effects: { fun: 10 },
        initialPrice: 20000,
        price: 20000,
        displayPrice: '20 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 36,
        requirements: { education: ['srednee_obrazovanie', 'devyat_klassov', 'treh_klassa', 'nauchitsya_chitat'] },
    },
    akademik: {
        title: 'Академик',
        description: 'Погружение в технологии',
        effects: { fun: 10 },
        initialPrice: 200000,
        price: 200000,
        displayPrice: '200 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 51,
        requirements: { education: ['vysshee_obrazovanie', 'srednee_obrazovanie', 'devyat_klassov', 'treh_klassa', 'nauchitsya_chitat'] },
    },
    professor: {
        title: 'Заниматься с профессором',
        description: 'Индивидуальные занятия',
        effects: {},
        initialPrice: 2000,
        price: 2000,
        displayPrice: '2 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 62,
        requirements: { education: ['nanjat_repetitora'] },
    },
    doktor_nauk: {
        title: 'Доктор наук',
        description: 'Практика в компании',
        effects: { fun: 10 },
        initialPrice: 500000,
        price: 500000,
        displayPrice: '500 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 70,
        requirements: { education: ['vysshee_obrazovanie', 'srednee_obrazovanie', 'devyat_klassov', 'treh_klassa', 'nauchitsya_chitat'] },
    },
    laboratoriya: {
        title: 'Купить себе лабораторию',
        description: 'Мировой опыт',
        effects: { fun: 10, food: 10, usdt: 0.02 },
        initialPrice: 3000000,
        price: 3000000,
        displayPrice: '3 000 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 75,
        requirements: { education: ['professor', 'nanjat_repetitora'] },
    },
    nobel: {
        title: 'Нобелевская премия',
        description: 'Децентрализованные финансы',
        effects: { fun: 10, food: 10, usdt: 100000 },
        initialPrice: 0,
        price: 0,
        displayPrice: '0$',
        currency: 'usdt',
        requiredLevel: 78,
        requirements: { education: ['doktor_nauk', 'vysshee_obrazovanie', 'srednee_obrazovanie', 'devyat_klassov', 'treh_klassa'] },
    },
    vmozgkomp: {
        title: 'Вживить в мозг компьютер',
        description: 'Высшая школа бизнеса',
        effects: {},
        initialPrice: 300000000,
        price: 300000000,
        displayPrice: '300 000 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 79,
        requirements: { education: ['laboratoriya', 'professor', 'nanjat_repetitora'] },
    },
    ocifrovat_soznanie: {
        title: 'Оцифровать сознание',
        description: 'Премиум-обучение',
        effects: {},
        initialPrice: 1000000000,
        price: 1000000000,
        displayPrice: '1 000 000 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 80,
        requirements: { education: ['vmozgkomp', 'laboratoriya', 'professor', 'nanjat_repetitora'] },
    },
};