export const CarsData = {
    bosikom: {
        title: 'Босиком',
        description: 'Пешком, но стильно',
        effects: { },
        initialPrice: 0,
        price: 0,
        displayPrice: '0$',
        currency: 'usdt',
        requiredLevel: 0,
    },
    noski: {
        title: 'Носки',
        description: 'Свобода и ветер',
        effects: { fun: 10 },
        initialPrice: 50,
        price: 50,
        displayPrice: '50$',
        currency: 'usdt',
        requiredLevel: 0,
    },
    tapochki: {
        title: 'Тапочки',
        description: 'Экономия и спорт',
        effects: { fun: 10 },
        initialPrice: 200,
        price: 200,
        displayPrice: '200$',
        currency: 'usdt',
        requiredLevel: 0,
    },
    krossovki: {
        title: 'Кроссовки',
        description: 'Городской ритм',
        effects: { fun: 10 },
        initialPrice: 500,
        price: 500,
        displayPrice: '500$',
        currency: 'usdt',
        requiredLevel: 12,
    },
    tufli: {
        title: 'Туфли',
        description: 'Модно и удобно',
        effects: { fun: 10 },
        initialPrice: 2000,
        price: 2000,
        displayPrice: '2 000$',
        currency: 'usdt',
        requiredLevel: 14,
        requirements: { car: ['krossovki'] },
    },
    skejt: {
        title: 'Скейт',
        description: 'Быстрее, чем пешком',
        effects: { fun: 10 },
        initialPrice: 3000,
        price: 3000,
        displayPrice: '3 000$',
        currency: 'usdt',
        requiredLevel: 17,
        requirements: { car: ['tufli', 'krossovki'] },
    },
    velosiped: {
        title: 'Велосипед',
        description: 'Скорость и драйв',
        effects: { fun: 10 },
        initialPrice: 10000,
        price: 10000,
        displayPrice: '10 000$',
        currency: 'usdt',
        requiredLevel: 33,
        requirements: { car: ['skejt', 'tufli', 'krossovki'] },
    },
    moped: {
        title: 'Мопед',
        description: 'Авто по подписке',
        effects: { fun: 10 },
        initialPrice: 30000,
        price: 30000,
        displayPrice: '30 000$',
        currency: 'usdt',
        requiredLevel: 50,
        requirements: { car: ['velosiped', 'skejt', 'tufli', 'krossovki'] },
    },
    zhiguli: {
        title: 'Жигули',
        description: 'Первый личный транспорт',
        effects: { fun: 10 },
        initialPrice: 70000,
        price: 70000,
        displayPrice: '70 000$',
        currency: 'usdt',
        requiredLevel: 51,
        requirements: { car: ['moped', 'velosiped', 'skejt', 'tufli', 'krossovki'] },
    },
    inomarka: {
        title: 'Иномарка',
        description: 'Комфорт и статус',
        effects: { fun: 10 },
        initialPrice: 90000,
        price: 90000,
        displayPrice: '90 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 58,
        requirements: { car: ['zhiguli', 'moped', 'velosiped', 'skejt', 'tufli'] },
    },
    lyuksovyi_avto: {
        title: 'Люксовый авто',
        description: 'Электро-стиль',
        effects: { fun: 10 },
        initialPrice: 500000,
        price: 500000,
        displayPrice: '500 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 67,
        requirements: { car: ['inomarka', 'zhiguli', 'moped', 'velosiped', 'skejt'] },
    },
    vertolet: {
        title: 'Вертолет',
        description: 'Для любых дорог',
        effects: { fun: 10 },
        initialPrice: 1200000,
        price: 1200000,
        displayPrice: '1 200 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 71,
        requirements: { car: ['lyuksovyi_avto', 'inomarka', 'zhiguli', 'moped', 'velosiped'] },
    },
    samolet: {
        title: 'Самолет',
        description: 'Скорость и стиль',
        effects: { fun: 10 },
        initialPrice: 4000000,
        price: 4000000,
        displayPrice: '4 000 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 78,
        requirements: { car: ['vertolet', 'lyuksovyi_avto', 'inomarka', 'zhiguli', 'moped'] },
    },
    shattl: {
        title: 'Шаттл',
        description: 'Мечта трейдера',
        effects: { fun: 10 },
        initialPrice: 40000000,
        price: 40000000,
        displayPrice: '40 000 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 79,
        requirements: { car: ['samolet', 'vertolet', 'lyuksovyi_avto', 'inomarka', 'zhiguli'] },
    },
    teleport: {
        title: 'Телепорт',
        description: 'Вершина успеха',
        effects: { fun: 10 },
        initialPrice: 400000000,
        price: 400000000,
        displayPrice: '400 000 000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 80,
        requirements: { car: ['shattl', 'samolet', 'vertolet', 'lyuksovyi_avto', 'inomarka'] },
    },
};