// TaskApartList.jsx
export const AppartamentData = {
    nadereve: {
        title: 'На дереве',
        emoji: '⛺',
        description: 'Минимум комфорта, максимум свободы',
        effects: { },
        initialPrice: 0,
        price: 0,
        displayPrice: '0$',
        currency: 'usdt',
        requiredLevel: 0,
        image: '',
    },
    musornyibak: {
        title: 'Мусорный бак',
        emoji: '🛏️',
        description: 'Общая комната для старта',
        effects: {  },
        initialPrice: 0,
        price: 0,
        displayPrice: '0$',
        currency: 'usdt',
        requiredLevel: 0,
        image: '',
    },
    korobka: {
        title: 'Коробка',
        emoji: '🚪',
        description: 'Собственное пространство',
        effects: { },
        initialPrice: 50,
        price: 50,
        displayPrice: '50$',
        currency: 'usdt',
        requiredLevel: 0,
        image: '',
    },
    shalash: {
        title: 'Шалаш',
        emoji: '🛋️',
        description: 'Маленькая, но своя',
        effects: { },
        initialPrice: 150,
        price: 150,
        displayPrice: '150$',
        currency: 'usdt',
        requiredLevel: 3,
        image: '',
        requirements: { appartament: 'korobka' },
    },
    podval: {
        title: 'Подвал',
        emoji: '🏢',
        description: 'Городская классика',
        effects: { },
        initialPrice: 500,
        price: 500,
        displayPrice: '500$',
        currency: 'usdt',
        requiredLevel: 4,
        image: '',
        requirements: { appartament: ['korobka', 'shalash'] },
    },
    cherdak: {
        title: 'Чердак',
        emoji: '🏬',
        description: 'Уют и комфорт',
        effects: {},
        initialPrice: 1000,
        price: 1000,
        displayPrice: '1000$',
        currency: 'usdt',
        requiredLevel: 16,
        image: '',
        requirements: { appartament: ['podval', 'shalash', 'korobka'] },
    },
    arendakomnaty: {
        title: 'Аренда комнаты',
        emoji: '🏚️',
        description: 'Современный стиль',
        effects: {},
        initialPrice: 5000,
        price: 5000,
        displayPrice: '5000$',
        currency: 'usdt',
        requiredLevel: 22,
        image: '',
        requirements: { education: ['nauchitsya_chitat'], appartament: ['cherdak', 'podval', 'shalash', 'korobka'] },
    },
    arendakvartiry: {
        title: 'Аренда квартиры',
        emoji: '🔑',
        description: 'Для семьи и друзей',
        effects: {},
        initialPrice: 3000,
        price: 3000,
        displayPrice: '3000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 37,
        image: '',
        requirements: { education: ['treh_klassa', 'nauchitsya_chitat'], appartament: ['arendakvartiry', 'cherdak', 'podval'] },
    },
    kvartira: {
        title: 'Квартира',
        emoji: '🌇',
        description: 'Вид на город сверху',
        effects: {},
        initialPrice: 80000,
        price: 80000,
        displayPrice: '80000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 48,
        image: '',
        requirements: { education: ['arendakvartiry', 'treh_klassa', 'nauchitsya_chitat'], appartament: ['arendakomnaty', 'cherdak'] },
    },
    penthaus: {
        title: 'Пентхаус',
        emoji: '🏖️',
        description: 'Роскошь и простор',
        effects: {},
        initialPrice: 550000,
        price: 550000,
        displayPrice: '550000 HBTRD',
        currency: 'hbtrd',
        requiredLevel: 57,
        image: '',
        requirements: { appartament: ['kvartira', 'arendakvartiry', 'arendakomnaty', 'cherdak'], education: ['treh_klassa', 'nauchitsya_chitat'] },
    },
    kottedzh: {
        title: 'Коттедж',
        emoji: '🏡',
        description: 'Загородная жизнь',
        effects: {},
        initialPrice: 1000000,
        price: 1000000,
        displayPrice: '1млн HBTRD',
        currency: 'hbtrd',
        requiredLevel: 69,
        image: '',
        requirements: { appartament: ['penthaus', 'kvartira', 'arendakvartiry'], education: ['treh_klassa', 'nauchitsya_chitat'] },
    },
    nedvizhimostzagr: {
        title: 'Недвижимость за границей',
        emoji: '🏛️',
        description: 'Символ успеха',
        effects: {},
        initialPrice: 7000000,
        price: 7000000,
        displayPrice: '7млн HBTRD',
        currency: 'hbtrd',
        requiredLevel: 70,
        image: '',
        requirements: { appartament: ['kottedzh', 'penthaus', 'kvartira', 'arendakvartiry'], education: ['treh_klassa'] },
    },
    svoiGostinica: {
        title: 'Своя гостинница',
        emoji: '🏰',
        description: 'Для избранных',
        effects: { health: 100, fun: 100, usdt: 200000 }, // 5% от 20млн
        initialPrice: 20000000,
        price: 20000000,
        displayPrice: '20млн HBTRD',
        currency: 'hbtrd',
        requiredLevel: 76,
        image: '',
        requirements: { education: ['vysshee_obrazovanie', 'srednee_obrazovanie', 'devyat_klassov', 'treh_klassa', 'nauchitsya_chitat'] },
    },
    svoiOstrov: {
        title: 'Свой остров',
        emoji: '🏝️',
        description: 'Технологии и комфорт',
        effects: { health: 100, fun: 100, usdt: 18000000 }, // 3% от 600млн
        initialPrice: 600000000,
        price: 600000000,
        displayPrice: '600млн HBTRD',
        currency: 'hbtrd',
        requiredLevel: 79,
        image: '',
        requirements: { education: ['obrazovanie_zagr', 'srednee_obrazovanie', 'devyat_klassov', 'treh_klassa', 'nauchitsya_chitat'] },
    },
    beliyDom: {
        title: 'Белый дом',
        emoji: '👑',
        description: 'Вершина роскоши',
        effects: { health: 100, fun: 100, hbtrd: 30000000 }, // 1% от 3млрд
        initialPrice: 3000000000,
        price: 3000000000,
        displayPrice: '3млрд HBTRD',
        currency: 'hbtrd',
        requiredLevel: 80,
        image: '',
        requirements: { education: ['akademik', 'vysshee_obrazovanie', 'srednee_obrazovanie', 'devyat_klassov', 'treh_klassa'] },
    },
};