// TaskApartList.jsx
export const AppartamentData = {
    box: {
        title: 'Коробка',
        description: 'Квадратная и просторная',
        effects: { food: 5, health: 5 },
        initialPrice: 0, // Бесплатно
        price: 0,
        displayPrice: '0$',
        currency: 'usdt',
        requiredLevel: 0,
        image: '',
      },
    trash: {
        title: 'Мусорный бак',
        description: 'Вонючий, но спасет от дождя',
        effects: { food: 5, health: 5 },
        initialPrice: 3,
        price: 3,
        displayPrice: '3$',
        currency: 'usdt',
        requiredLevel: 1,
        image: '',
        },
    tent: {
        title: 'Шалаш',
        description: 'Воткнул колышки и ветер не помеха',
        effects: { food: 5, health: 5 },
        initialPrice: 10,
        price: 10,
        displayPrice: '10$',
        currency: 'usdt',
        requiredLevel: 4,
        image: '',  
        },
    basement: {
        title: 'Подвал',
        description: 'Сыро, но тепло',
        effects: { food: 5, health: 5 },
        initialPrice: 10,
        price: 10,
        displayPrice: '10$',
        currency: 'usdt',
        requiredLevel: 7,
        image: '',
        },
    attic: {
        title: 'Чердак',
        description: 'Можно и голубей покормить и поймать',
        effects: { food: 5, health: 5 },
        initialPrice: 100,
        price: 100,
        displayPrice: '100$',
        currency: 'usdt',
        requiredLevel: 10,
        image: '',
        },
  };